server:
  port: 8099

spring:
  h2:
    console:
      enabled: true
      path: /h2db
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./hello
    username: hello
    password: world
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
